/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#26e6ff",
        "primary": "#8eff71",
        "on-tertiary-fixed": "#003f43",
        "secondary-container": "#006875",
        "secondary-dim": "#00d4ec",
        "tertiary-dim": "#00deea",
        "on-tertiary-fixed-variant": "#005e63",
        "on-surface-variant": "#acaab1",
        "on-error": "#450900",
        "outline-variant": "#48474d",
        "on-secondary-fixed": "#003a42",
        "surface-bright": "#2c2b33",
        "tertiary-container": "#17eefa",
        "surface-container-lowest": "#000000",
        "primary-fixed-dim": "#2be800",
        "on-background": "#f9f5fd",
        "inverse-surface": "#fcf8ff",
        "surface-container-low": "#131319",
        "primary-container": "#2ff801",
        "surface-container-highest": "#25252d",
        "on-secondary": "#004d57",
        "inverse-primary": "#106f00",
        "on-secondary-container": "#e8fbff",
        "tertiary-fixed": "#17eefa",
        "on-primary-fixed-variant": "#0d6200",
        "on-tertiary": "#005d62",
        "on-primary": "#0d6100",
        "on-error-container": "#ffd2c8",
        "error-dim": "#d53d18",
        "error": "#ff7351",
        "surface-container": "#19191f",
        "outline": "#76747b",
        "surface-variant": "#25252d",
        "secondary": "#00e3fd",
        "error-container": "#b92902",
        "background": "#0e0e13",
        "on-secondary-fixed-variant": "#005964",
        "surface-container-high": "#1f1f26",
        "surface": "#0e0e13",
        "secondary-fixed-dim": "#00d7f0",
        "tertiary-fixed-dim": "#00deea",
        "tertiary": "#88f6ff",
        "on-primary-container": "#0b5800",
        "primary-dim": "#2be800",
        "inverse-on-surface": "#55545b",
        "on-primary-fixed": "#064200",
        "surface-tint": "#8eff71",
        "surface-dim": "#0e0e13",
        "primary-fixed": "#2ff801",
        "on-surface": "#f9f5fd",
        "on-tertiary-container": "#005458"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      }
    },
  },
  plugins: [],
}
